--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.22
-- Dumped by pg_dump version 13.0 (Ubuntu 13.0-1.pgdg18.04+1)

-- Started on 2022-12-20 15:00:05 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

--
-- TOC entry 185 (class 1259 OID 247518)
-- Name: a; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.a (
    id integer NOT NULL
);


ALTER TABLE public.a OWNER TO postgres;

--
-- TOC entry 186 (class 1259 OID 247523)
-- Name: b; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.b (
    id integer NOT NULL
);


ALTER TABLE public.b OWNER TO postgres;

--
-- TOC entry 187 (class 1259 OID 247528)
-- Name: c; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.c (
    id integer NOT NULL
);


ALTER TABLE public.c OWNER TO postgres;

--
-- TOC entry 188 (class 1259 OID 247533)
-- Name: d; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.d (
    id integer NOT NULL
);


ALTER TABLE public.d OWNER TO postgres;

--
-- TOC entry 189 (class 1259 OID 247538)
-- Name: e; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.e (
    id integer NOT NULL
);


ALTER TABLE public.e OWNER TO postgres;

--
-- TOC entry 190 (class 1259 OID 247543)
-- Name: f; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.f (
    id integer NOT NULL
);


ALTER TABLE public.f OWNER TO postgres;

--
-- TOC entry 191 (class 1259 OID 248640)
-- Name: g; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.g (
    id1 integer NOT NULL,
    id2 character varying(10) NOT NULL
);


ALTER TABLE public.g OWNER TO postgres;

--
-- TOC entry 192 (class 1259 OID 248645)
-- Name: h; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.h (
    id2 character varying(10) NOT NULL,
    id1 integer NOT NULL
);


ALTER TABLE public.h OWNER TO postgres;

--
-- TOC entry 2204 (class 0 OID 247518)
-- Dependencies: 185
-- Data for Name: a; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.a (id) FROM stdin;
\.


--
-- TOC entry 2205 (class 0 OID 247523)
-- Dependencies: 186
-- Data for Name: b; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.b (id) FROM stdin;
\.


--
-- TOC entry 2206 (class 0 OID 247528)
-- Dependencies: 187
-- Data for Name: c; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.c (id) FROM stdin;
\.


--
-- TOC entry 2207 (class 0 OID 247533)
-- Dependencies: 188
-- Data for Name: d; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.d (id) FROM stdin;
\.


--
-- TOC entry 2208 (class 0 OID 247538)
-- Dependencies: 189
-- Data for Name: e; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.e (id) FROM stdin;
\.


--
-- TOC entry 2209 (class 0 OID 247543)
-- Dependencies: 190
-- Data for Name: f; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.f (id) FROM stdin;
\.


--
-- TOC entry 2210 (class 0 OID 248640)
-- Dependencies: 191
-- Data for Name: g; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.g (id1, id2) FROM stdin;
\.


--
-- TOC entry 2211 (class 0 OID 248645)
-- Dependencies: 192
-- Data for Name: h; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.h (id2, id1) FROM stdin;
\.


--
-- TOC entry 2064 (class 2606 OID 247522)
-- Name: a a_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.a
    ADD CONSTRAINT a_pkey PRIMARY KEY (id);


--
-- TOC entry 2066 (class 2606 OID 247527)
-- Name: b b_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b
    ADD CONSTRAINT b_pkey PRIMARY KEY (id);


--
-- TOC entry 2068 (class 2606 OID 247532)
-- Name: c c_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.c
    ADD CONSTRAINT c_pkey PRIMARY KEY (id);


--
-- TOC entry 2070 (class 2606 OID 247537)
-- Name: d d_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.d
    ADD CONSTRAINT d_pkey PRIMARY KEY (id);


--
-- TOC entry 2072 (class 2606 OID 247542)
-- Name: e e_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.e
    ADD CONSTRAINT e_pkey PRIMARY KEY (id);


--
-- TOC entry 2074 (class 2606 OID 247547)
-- Name: f f_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.f
    ADD CONSTRAINT f_pkey PRIMARY KEY (id);


--
-- TOC entry 2076 (class 2606 OID 248644)
-- Name: g g_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.g
    ADD CONSTRAINT g_pkey PRIMARY KEY (id1, id2);


--
-- TOC entry 2078 (class 2606 OID 248649)
-- Name: h h_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.h
    ADD CONSTRAINT h_pkey PRIMARY KEY (id2, id1);


--
-- TOC entry 2079 (class 2606 OID 247548)
-- Name: a a_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.a
    ADD CONSTRAINT a_1 FOREIGN KEY (id) REFERENCES public.b(id);


--
-- TOC entry 2080 (class 2606 OID 247553)
-- Name: a a_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.a
    ADD CONSTRAINT a_2 FOREIGN KEY (id) REFERENCES public.c(id);


--
-- TOC entry 2081 (class 2606 OID 247558)
-- Name: b b_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b
    ADD CONSTRAINT b_1 FOREIGN KEY (id) REFERENCES public.e(id);


--
-- TOC entry 2082 (class 2606 OID 247563)
-- Name: c c_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.c
    ADD CONSTRAINT c_1 FOREIGN KEY (id) REFERENCES public.d(id);


--
-- TOC entry 2083 (class 2606 OID 248627)
-- Name: c c_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.c
    ADD CONSTRAINT c_2 FOREIGN KEY (id) REFERENCES public.e(id);


--
-- TOC entry 2084 (class 2606 OID 248632)
-- Name: e e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.e
    ADD CONSTRAINT e FOREIGN KEY (id) REFERENCES public.f(id);


--
-- TOC entry 2085 (class 2606 OID 247568)
-- Name: f f_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.f
    ADD CONSTRAINT f_1 FOREIGN KEY (id) REFERENCES public.a(id);


--
-- TOC entry 2086 (class 2606 OID 248650)
-- Name: h h_id1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.h
    ADD CONSTRAINT h_id1_fkey FOREIGN KEY (id1, id2) REFERENCES public.g(id1, id2);


-- Completed on 2022-12-20 15:00:05 CET

--
-- PostgreSQL database dump complete
--

