# build with
# docker build -t ontop_psql .
# run with   
# docker run --name ontop_psql_running -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d ontop_psql

FROM postgres:9.5

RUN mkdir -p /tmp/sql_scripts/

# copying all SQL files to this folder will automatically put them in the default DB
COPY sql/all/*.sql /docker-entrypoint-initdb.d/

#COPY init_docker_postgres.sh /docker-entrypoint-initdb.d/


