FROM mysql:5.7.9

RUN mkdir -p /tmp/sql_scripts/

# copying all SQL files to this folder will automatically put them in the default DB
COPY sql/all/*.sql /docker-entrypoint-initdb.d/

ENV MYSQL_DATABASE ontop




