
FROM alexeiled/docker-oracle-xe-11g


RUN mkdir -p /tmp/sql_scripts/

COPY sql/all/*.sql /tmp/sql_scripts/

USER root
ENV HOME /root
COPY load-scripts-oracle.sh .

ENV ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
ENV PATH=$ORACLE_HOME/bin:$PATH
ENV ORACLE_SID=XE

RUN sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora; \
	service oracle-xe start; \
    bash load-scripts-oracle.sh \
    service oracle-xe stop; \






# docker build -t ontop_oracle .


#  docker pull alexeiled/docker-oracle-xe-11g
# docker run -d -p 49160:22 -p 49161:1521 -p 49162:8080 alexeiled/docker-oracle-xe-11g

# based one https://hub.docker.com/r/alexeiled/docker-oracle-xe-11g/

# connect with

# hostname: localhost
# port: 49161
# sid: xe
# username: system
# password: oracle

# ssh root@localhost -p 49160
# password: admin

# password for SYS = oracle

# Oracle applicaiton expresss

# url: http://localhost:49162/apex
# workspace: INTERNAL
# user: ADMIN
# password: oracle


