
FROM ibmcom/db2express-c


RUN mkdir -p /tmp/sql_scripts/

COPY sql/all/*.sql /tmp/sql_scripts/
COPY load-scripts-db2.sh /home/db2inst1/


RUN chown db2inst1:db2inst1 /home/db2inst1/load-scripts-db2.sh 
RUN chmod 777 /home/db2inst1/load-scripts-db2.sh

ENV DB2INST1_PASSWORD db2inst1-pwd
ENV LICENSE=accept

ENV DB2EXPRESSC_DATADIR /home/db2inst1/data
ENV DB2EXPRESSC_SHA256 a5c9a3231054047f1f63e7144e4da49c4feaca25d8fce4ad97539d72abfc93d0
ENV DB2EXPRESSC_URL https://s3.amazonaws.com/db2-expc105-64bit-centos/v10.5fp5_linuxx64_expc.tar.gz

RUN su - db2inst1 -c "db2start && db2set DB2COMM=TCPIP && /home/db2inst1/load-scripts-db2.sh" \
	&& su - db2inst1 -c "db2stop force"

