PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>
SELECT DISTINCT * 
WHERE {
   ?x a :Address; :addressID ?id; :inStreet ?street; :inCity ?city; :inCountry ?country; :inState ?state; :hasNumber ?number.
 }
ORDER BY DESC(?city)