CREATE TABLE COMPANY(NAME VARCHAR(20));
CREATE TABLE DEPARTMENT( ID INT, NAME VARCHAR(20), C_NAME VARCHAR(20));
CREATE TABLE EMPLOYEE (NAME VARCHAR(20), DEPID INT);

INSERT INTO COMPANY(NAME) VALUES ('A');
INSERT INTO COMPANY(NAME) VALUES ('B');

INSERT INTO DEPARTMENT (ID, NAME, C_NAME)  VALUES ('1', 'HR', 'A');
INSERT INTO DEPARTMENT (ID, NAME, C_NAME)  VALUES ('2', 'ADMIN', 'A');
INSERT INTO DEPARTMENT (ID, NAME, C_NAME)  VALUES ('2', 'ADMIN', 'B');

INSERT INTO  EMPLOYEE (NAME, DEPID) VALUES ('mark','1');
INSERT INTO  EMPLOYEE (NAME, DEPID) VALUES ('lisa','2');
INSERT INTO  EMPLOYEE (NAME, DEPID) VALUES ('sara','2');