package it.unibz.inf.ontop.injection;

import com.google.common.collect.ImmutableList;
import it.unibz.inf.ontop.exception.DuplicateMappingException;
import it.unibz.inf.ontop.mapping.MappingMetadata;
import it.unibz.inf.ontop.model.SQLPPMappingAxiom;
import it.unibz.inf.ontop.model.SQLPPMapping;

/**
 * Some object instantiations may throw exceptions that
 * should be expected.
 *
 * This factory is dedicated to them.
 *
 * The drawback of this approach is that
 * no implementation of this factory can be automatically
 * generated by Guice.
 */
public interface OBDAFactoryWithException {

    SQLPPMapping createSQLPreProcessedMapping(ImmutableList<SQLPPMappingAxiom> newMappings,
                                              MappingMetadata metadata) throws DuplicateMappingException;
}
