PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>

SELECT DISTINCT $x $date 
WHERE { 
   $x a :Transaction; :transactionDate $date; :amountOfTransaction "12.6"^^<http://www.w3.org/2001/XMLSchema#decimal> . 
}