# BSBM-07: retrieve in-depth information about a specific product including offers and reviews
# PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
# PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# PREFIX foaf: <http://xmlns.com/foaf/0.1/>
# PREFIX rev: <http://purl.org/stuff/rev#>
# PREFIX dc: <http://purl.org/dc/elements/1.1/>
# BASE <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
# 
# SELECT
#     ?productLabel ?offer ?price ?vendor ?vendorTitle
#     ?review ?revTitle ?reviewer ?revName ?rating1 ?rating2
# {
#     <dataFromProducer/Product${product:percent}> rdfs:label ?productLabel .
#     OPTIONAL {
#         ?offer bsbm:product <dataFromProducer/Product${product:percent}> .
#         ?offer bsbm:price ?price .
#         ?offer bsbm:vendor ?vendor .
#         ?vendor rdfs:label ?vendorTitle .
#         ?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#DE> .
#         ?offer dc:publisher ?vendor .
#         ?offer bsbm:validTo ?date .
#         FILTER (?date > "${offer_validto_lo:none}"^^xsd:date)
#     }
#     OPTIONAL {
#         ?review bsbm:reviewFor <dataFromProducer/Product${product:percent}> .
#         ?review rev:reviewer ?reviewer .
#         ?reviewer foaf:name ?revName .
#         ?review dc:title ?revTitle .
#         OPTIONAL { ?review bsbm:rating1 ?rating1 }
#         OPTIONAL { ?review bsbm:rating2 ?rating2 }
#     }
# }
#
# instantiate sample variables
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
BASE <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>

SELECT
    ?productLabel ?offer ?price ?vendor ?vendorTitle
    ?review ?revTitle ?reviewer ?revName ?rating1 ?rating2
{
    <dataFromProducer/Product94> rdfs:label ?productLabel .  # product = 94
    OPTIONAL {
        ?offer bsbm:product <dataFromProducer/Product94> .
        ?offer bsbm:price ?price .
        ?offer bsbm:vendor ?vendor .
        ?vendor rdfs:label ?vendorTitle .
        ?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#DE> .
        ?offer dc:publisher ?vendor .
        ?offer bsbm:validTo ?date .
        FILTER (?date > "2008-06-13"^^xsd:date)  # offer_validto_lo = 2008-06-13
    }
    OPTIONAL {
        ?review bsbm:reviewFor <dataFromProducer/Product94> .
        ?review rev:reviewer ?reviewer .
        ?reviewer foaf:name ?revName .
        ?review dc:title ?revTitle .
        OPTIONAL { ?review bsbm:rating1 ?rating1 }
        OPTIONAL { ?review bsbm:rating2 ?rating2 }
    }
}