# BSBM-EXT-14: get offers fulfill specific requirements for products of a specific type (based on BSBM-10)
# PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
# PREFIX dc: <http://purl.org/dc/elements/1.1/>
# BASE <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
# 
# SELECT DISTINCT ?offer ?product ?price
# {
#     ?product dc:identifier ?id .
#     FILTER (${product_lo:none} <= ?id && ?id <= ${product_hi:none})
#     ?offer bsbm:product ?product .
#     ?offer bsbm:vendor ?vendor .
#     ?offer dc:publisher ?vendor .
#     ?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#US> .
#     ?offer bsbm:deliveryDays ?deliveryDays .
#     FILTER (?deliveryDays <= 3)
#     ?offer bsbm:price ?price .
#     ?offer bsbm:validTo ?date .
# }
#
# instantiate sample variables
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
BASE <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>

SELECT DISTINCT ?offer ?product ?price
{
    ?product dc:identifier ?id .
    FILTER (1 <= ?id && ?id <= 500)
    ?offer bsbm:product ?product .
    ?offer bsbm:vendor ?vendor .
    ?offer dc:publisher ?vendor .
    ?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#US> .
    ?offer bsbm:deliveryDays ?deliveryDays .
    FILTER (?deliveryDays <= 3)
    ?offer bsbm:price ?price .
    ?offer bsbm:validTo ?date .
}