# BSBM-EXT-15: export information about offers for products of a specific type (based on BSBM-12)
# PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
# PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# PREFIX dc: <http://purl.org/dc/elements/1.1/>
# PREFIX foaf: <http://xmlns.com/foaf/0.1/>
# BASE <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
# 
# SELECT
#     ?offer ?product ?productlabel ?vendor ?vendorname
#     ?offerURL ?price ?deliveryDays ?validTo
# {
#     ?product dc:identifier ?id .
#     FILTER (${product_lo:none} <= ?id && ?id <= ${product_hi:none})
#     ?offer bsbm:product ?product .
#     ?product rdfs:label ?productlabel .
#     ?offer bsbm:vendor ?vendor .
#     ?vendor rdfs:label ?vendorname .
#     ?vendor foaf:homepage ?vendorhomepage .
#     ?offer bsbm:offerWebpage ?offerURL .
#     ?offer bsbm:price ?price .
#     ?offer bsbm:deliveryDays ?deliveryDays .
#     ?offer bsbm:validTo ?validTo
# }
#
# instantiate sample variables
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
BASE <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>

SELECT
    ?offer ?product ?productlabel ?vendor ?vendorname
    ?offerURL ?price ?deliveryDays ?validTo
{
    ?product dc:identifier ?id .
    FILTER (1 <= ?id && ?id <= 500)
    ?offer bsbm:product ?product .
    ?product rdfs:label ?productlabel .
    ?offer bsbm:vendor ?vendor .
    ?vendor rdfs:label ?vendorname .
    ?vendor foaf:homepage ?vendorhomepage .
    ?offer bsbm:offerWebpage ?offerURL .
    ?offer bsbm:price ?price .
    ?offer bsbm:deliveryDays ?deliveryDays .
    ?offer bsbm:validTo ?validTo
}