PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://www.semanticweb.org/ontologies/2011/10/iLogOntology.owl#>  

# Quanti ITU passano su una particolare route (ILOG)
# 

SELECT DISTINCT ?route ?itu ?ituevent1
WHERE {
?ituevent1 :happensToITU ?itu;
	:happensOnTrain ?train;
	:hasEventTime ?time1.
?train :isAssignedToRoute ?route.
FILTER(?time1 < "2011-11-11T12:00:00.000Z"^^xsd:dateTime)
}
ORDER BY ?route ?itu

