package it.unibz.inf.ontop.answering.reformulation.rewriting.impl;

import com.google.common.collect.*;
import com.google.inject.Inject;
import com.google.inject.assistedinject.Assisted;
import it.unibz.inf.ontop.answering.reformulation.rewriting.ImmutableCQContainmentCheck;
import it.unibz.inf.ontop.answering.reformulation.rewriting.ImmutableLinearInclusionDependenciesTools;
import it.unibz.inf.ontop.datalog.ImmutableLinearInclusionDependency;
import it.unibz.inf.ontop.model.atom.AtomPredicate;
import it.unibz.inf.ontop.model.atom.DataAtom;
import it.unibz.inf.ontop.model.term.Variable;
import it.unibz.inf.ontop.model.term.VariableOrGroundTerm;
import it.unibz.inf.ontop.utils.ImmutableCollectors;

import java.util.*;

public class ImmutableCQContainmentCheckUnderLIDs implements ImmutableCQContainmentCheck {

    private final Map<ImmutableList<DataAtom>, ImmutableMultimap<AtomPredicate, DataAtom>> chaseCache = new HashMap<>();
    private final ImmutableMultimap<AtomPredicate, ImmutableLinearInclusionDependency<AtomPredicate>> dependencies;

    private final ImmutableHomomorphismUtilities homomorphismUtilities;
    private final ImmutableLinearInclusionDependenciesTools inclusionDependencyTools;

    @Inject
    public ImmutableCQContainmentCheckUnderLIDs(@Assisted ImmutableMultimap<AtomPredicate, ImmutableLinearInclusionDependency<AtomPredicate>> dependencies,
                                                ImmutableHomomorphismUtilities homomorphismUtilities, ImmutableLinearInclusionDependenciesTools inclusionDependencyTools) {
        this.dependencies = dependencies;
        this.homomorphismUtilities = homomorphismUtilities;
        this.inclusionDependencyTools = inclusionDependencyTools;
    }

    @Override
    public boolean isContainedIn(ImmutableList<Variable> av1, ImmutableList<DataAtom> atoms1, ImmutableList<Variable> av2, ImmutableList<DataAtom> atoms2) {

        final ImmutableMultimap<AtomPredicate, DataAtom> chase1 = getChasedAtoms(atoms1);

        // just to speed up the check in case there can be no match
        if (atoms2.stream().anyMatch(a -> !chase1.containsKey(a.getPredicate())))
            return false;

        Map<Variable, VariableOrGroundTerm> sb = new HashMap<>();
        // get the substitution for the answer variables first
        // this will ensure that all answer variables are mapped either to constants or
        //       to answer variables in the base (but not to the labelled nulls generated by the chase)
        boolean headResult = homomorphismUtilities.extendHomomorphism(sb, av2, av1);
        if (!headResult)
            return false;

        return homomorphismUtilities.computeSomeHomomorphism(sb, atoms2, chase1).isPresent();
    }

    ImmutableMultimap<AtomPredicate, DataAtom> getChasedAtoms(ImmutableList<DataAtom> atoms) {
        ImmutableMultimap<AtomPredicate, DataAtom> result = chaseCache.get(atoms);
        if (result == null) {
            result = Sets.union(ImmutableSet.copyOf(atoms),
                            (dependencies == null)
                            ? ImmutableSet.of()
                            : atoms.stream()
                                .flatMap(a -> inclusionDependencyTools.chaseAtom(a, dependencies.get(a.getPredicate())).stream())
                                .collect(ImmutableCollectors.toSet())).stream()
                    .collect(ImmutableCollectors.toMultimap(DataAtom::getPredicate, a -> a));
            chaseCache.put(atoms, result);
        }
        return result;
    }




}
