PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>
SELECT DISTINCT $fname $ln $securitynum WHERE { 
	$member a :StockExchangeMember. 
	$member :tradesOnBehalfOf $client1. 
	$client1 a :PhysicalPerson. 
	$member :firstName $fname. 
	$member :lastName $ln. 
	$member :ssn $securitynum
 }