PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX  :  <http://example/>
SELECT  ?lit (concat(?lit, "appended"^^xsd:string, "three"^^xsd:string, "strings"^^xsd:string) as ?c)
 WHERE {
   	?X :stringTypedLiteral ?lit . 
}
