PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX  :  <http://example/>
SELECT  ?lit (concat(?lit, "appended", "three"@en, "strings"@en) as ?c)
 WHERE {
   	?X :stringTypedLiteral ?lit . 
}
