/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DependencyTabPane.java
 *
 * Created on Aug 12, 2009, 10:18:26 AM
 */
package inf.unibz.it.obda.gui.swing.dependencies.panel;

import inf.unibz.it.obda.api.controller.APIController;
import inf.unibz.it.obda.domain.DataSource;
import inf.unibz.it.obda.gui.swing.constraints.panel.CheckConstraintsPanel;
import inf.unibz.it.obda.gui.swing.constraints.panel.ForeignKeyConstraintsPanel;
import inf.unibz.it.obda.gui.swing.constraints.panel.PrimaryKeyConstraintPanel;
import inf.unibz.it.obda.gui.swing.constraints.panel.UniquenessConstraintPanel;
import inf.unibz.it.obda.gui.swing.datasource.DatasourceSelectorListener;
import inf.unibz.it.obda.gui.swing.preferences.OBDAPreferences;

/**
 *The tab pane which is added to the OBDA tab of Protege4
 *
 * @author Manfred Gerstgrasser
 * 		   KRDB Research Center, Free University of Bolzano/Bozen, Italy 
 */
public class DependencyTabPane extends javax.swing.JPanel implements DatasourceSelectorListener {

    private APIController apic = null;
    private OBDAPreferences preference = null;
    
    /**
     * The constructor.
     */
    public DependencyTabPane(APIController apic, OBDAPreferences preference) {
    	this.apic = apic;
    	this.preference = preference;

      initComponents();
    }
    
    @Override
    public void datasourceChanged(DataSource oldSource, DataSource newSource) {
      
      pnlPrimaryKeyConstraint.datasourceChanged(oldSource, newSource);
      pnlForeignKeyConstraint.datasourceChanged(oldSource, newSource);
      pnlCheckConstraint.datasourceChanged(oldSource, newSource);
      pnlUniquenessConstraint.datasourceChanged(oldSource, newSource);
      pnlInclusionDependency.datasourceChanged(oldSource, newSource);
      pnlDisjointnessDependency.datasourceChanged(oldSource, newSource);
      pnlFunctionalDependency.datasourceChanged(oldSource, newSource);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabConstraints = new javax.swing.JTabbedPane();
        pnlPrimaryKeyConstraint = new PrimaryKeyConstraintPanel(apic, preference);
        pnlForeignKeyConstraint = new ForeignKeyConstraintsPanel(apic, preference);
        pnlCheckConstraint = new CheckConstraintsPanel(apic, preference);
        pnlUniquenessConstraint = new UniquenessConstraintPanel(apic, preference);
        pnlInclusionDependency = new InclusionDependencyTreePane(apic, preference);
        pnlDisjointnessDependency = new DisjoinednessAssertionTreePane(apic, preference);
        pnlFunctionalDependency = new FunctionalDepTreePane(apic, preference);

        setMinimumSize(new java.awt.Dimension(600, 300));
        setLayout(new java.awt.BorderLayout());
        tabConstraints.addTab("Primary Key Constraint", pnlPrimaryKeyConstraint);
        tabConstraints.addTab("Foreign Key Constraint", pnlForeignKeyConstraint);
        tabConstraints.addTab("Check Constraint", pnlCheckConstraint);
        tabConstraints.addTab("Uniqueness Constraint", pnlUniquenessConstraint);
        tabConstraints.addTab("Inclusion Dependency", pnlInclusionDependency);
        tabConstraints.addTab("Disjointness Dependency", pnlDisjointnessDependency);
        tabConstraints.addTab("Functional Dependency", pnlFunctionalDependency);

        add(tabConstraints, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CheckConstraintsPanel pnlCheckConstraint;
    private DisjoinednessAssertionTreePane pnlDisjointnessDependency;
    private ForeignKeyConstraintsPanel pnlForeignKeyConstraint;
    private FunctionalDepTreePane pnlFunctionalDependency;
    private InclusionDependencyTreePane pnlInclusionDependency;
    private PrimaryKeyConstraintPanel pnlPrimaryKeyConstraint;
    private UniquenessConstraintPanel pnlUniquenessConstraint;
    private javax.swing.JTabbedPane tabConstraints;
    // End of variables declaration//GEN-END:variables

}
