CREATE TABLE "SYSTEM".Book (
    bk_code NUMBER(9,0),
	bk_title VARCHAR2(100)
   ) ;
   
CREATE TABLE "SYSTEM".Bookwriter (
    bk_code NUMBER(9,0),
	wr_code NUMBER(9,0)
   ) ;
   
CREATE TABLE "SYSTEM".Edition (
    ed_code NUMBER(9,0),
	ed_year NUMBER(9,0),
	bk_code NUMBER(9,0)
   ) ;

CREATE TABLE "SYSTEM".Writer (
    wr_code NUMBER(9,0),
	wr_name VARCHAR2(100)
   ) ;

ALTER TABLE "SYSTEM".Book ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (bk_code) ENABLE;

ALTER TABLE "SYSTEM".Bookwriter ADD CONSTRAINT "FK_BOOK_WRITER" FOREIGN KEY (bk_code)
    REFERENCES "SYSTEM".Book(bk_code) ENABLE;

ALTER TABLE "SYSTEM".Edition ADD CONSTRAINT "PK_EDITION" PRIMARY KEY (ed_code) ENABLE;
ALTER TABLE "SYSTEM".Edition ADD CONSTRAINT "FK_BOOK_EDITION" FOREIGN KEY (bk_code)
    REFERENCES "SYSTEM".Book(bk_code) ENABLE;

ALTER TABLE "SYSTEM".Writer ADD CONSTRAINT "PK_WRITER" PRIMARY KEY (wr_code) ENABLE;

ALTER TABLE "SYSTEM".Bookwriter ADD CONSTRAINT "FK_WRITER_BOOK" FOREIGN KEY (wr_code)
    REFERENCES "SYSTEM".Writer(wr_code) ENABLE;