/***
 * Copyright (c) 2008, Mariano Rodriguez-Muro.
 * All rights reserved.
 *
 * The OBDA-API is licensed under the terms of the Lesser General Public
 * License v.3 (see OBDAAPI_LICENSE.txt for details). The components of this
 * work include:
 * 
 * a) The OBDA-API developed by the author and licensed under the LGPL; and, 
 * b) third-party components licensed under terms that may be different from 
 *   those of the LGPL.  Information about such licenses can be found in the 
 *   file named OBDAAPI_3DPARTY-LICENSES.txt.
 */

package inf.unibz.it.obda.gui.swing.dataquery.panel;

import inf.unibz.it.obda.api.controller.QueryController;
import inf.unibz.it.obda.gui.swing.querycontroller.tree.QueryControllerGroup;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Vector;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * 
 * @author mariano
 */

public class SaveQueryPanel extends javax.swing.JPanel {

	private String NEWGROUP = "New group...";
	private String NOGROUP = "No group...";
	private JDialog parent = null;
	private String query = null;
	private String currentGroup = null;
	private String currentId = null;
	private QueryController queryController = null;

	/**
	 * 
	 * @param query
	 * @param parent
	 * @param queryController
	 */
	public SaveQueryPanel(String query, JDialog parent,
			QueryController queryController) {
		this.queryController = queryController;
		currentGroup = null;
		currentId = null;
		initComponents();
		initCombo();
		this.parent = parent;
		this.query = query;

	}

	/**
	 * Creates new form SaveQueryPanel and use the parameters currentGroup and
	 * currentId to initialize the JDialog
	 */
	public SaveQueryPanel(String query, JDialog parent,
			QueryController queryController, String currentGroup,
			String currentId) {

		this.queryController = queryController;
		this.currentGroup = currentGroup;
		this.currentId = currentId;
		initComponents();
		initCombo();
		this.parent = parent;
		this.query = query;

		// GUIUtils.setAntializaing(this, true);
	}

	/**
	 * 
	 * @param query
	 * @param parent
	 * @param queryController
	 * @param currentId
	 */
	public SaveQueryPanel(String query, JDialog parent,
			QueryController queryController, String currentId) {

		this.queryController = queryController;
		this.currentGroup = null;
		this.currentId = currentId;
		initComponents();
		initCombo();
		this.parent = parent;
		this.query = query;

		// GUIUtils.setAntializaing(this, true);
	}

	private void initCombo() {
		comboGroups.removeAllItems();
		comboGroups.insertItemAt(this.NOGROUP, comboGroups.getItemCount());
		QueryController qcontroller = queryController;
		Vector<QueryControllerGroup> groups = qcontroller.getGroups();

		for (QueryControllerGroup queryGroup : groups) {
			comboGroups.insertItemAt(queryGroup.getID(), comboGroups
					.getItemCount());
		}
		comboGroups.insertItemAt(this.NEWGROUP, comboGroups.getItemCount());
		comboGroups.addItemListener(new ItemListener() {

			public void itemStateChanged(ItemEvent e) {
				String name = (String) e.getItem();
				if (name.equals(NEWGROUP)) {
					fieldGroupNAme.setEnabled(true);
				} else
					fieldGroupNAme.setEnabled(false);

			}

		});
		if (currentGroup == null) {
			comboGroups.setSelectedItem(this.NOGROUP);
			fieldQueryID.setText(currentId);
		} else if (currentGroup != null) {
			comboGroups.setSelectedItem(this.currentGroup);
			fieldQueryID.setText(currentId);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel7 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		fieldQueryID = new javax.swing.JTextField();
		comboGroups = new javax.swing.JComboBox();
		fieldGroupNAme = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		buttonAccept = new javax.swing.JButton();
		buttonCancel = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		setMinimumSize(new java.awt.Dimension(290, 166));
		setPreferredSize(new java.awt.Dimension(290, 166));
		jLabel7.setBackground(new java.awt.Color(153, 0, 0));
		jLabel7.setFont(new java.awt.Font("Arial", 1, 11));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel7.setText("  SAVE QUERY ");
		jLabel7.setAlignmentX(10.0F);
		jLabel7.setFocusable(false);
		jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
		jLabel7.setIconTextGap(10);
		jLabel7.setMinimumSize(new java.awt.Dimension(25, 25));
		jLabel7.setOpaque(true);
		jLabel7.setPreferredSize(new java.awt.Dimension(121, 20));
		add(jLabel7, java.awt.BorderLayout.NORTH);

		jPanel1.setLayout(new java.awt.GridBagLayout());

		jPanel1.setMinimumSize(new java.awt.Dimension(430, 270));
		jPanel1.setPreferredSize(new java.awt.Dimension(430, 270));
		jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
		jLabel1.setText("<html>Insert an ID and group  for this query.</html>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
		jPanel1.add(jLabel1, gridBagConstraints);

		jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
		jLabel2.setText("ID:");
		jLabel2.setPreferredSize(new java.awt.Dimension(100, 20));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
		jPanel1.add(jLabel2, gridBagConstraints);

		jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
		jLabel4.setText("Group");
		jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
		jPanel1.add(jLabel4, gridBagConstraints);

		jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
		jLabel5.setText("Group Name:");
		jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
		jPanel1.add(jLabel5, gridBagConstraints);

		fieldQueryID.setMinimumSize(new java.awt.Dimension(150, 22));
		fieldQueryID.setNextFocusableComponent(comboGroups);
		fieldQueryID.setPreferredSize(new java.awt.Dimension(150, 22));
		fieldQueryID.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fieldQueryIDActionPerformed(evt);
			}
		});

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
		jPanel1.add(fieldQueryID, gridBagConstraints);
		comboGroups.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "No group..." }));
		comboGroups.setNextFocusableComponent(fieldGroupNAme);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(comboGroups, gridBagConstraints);

		fieldGroupNAme.setEnabled(false);
		fieldGroupNAme.setMinimumSize(new java.awt.Dimension(150, 22));
		fieldGroupNAme.setNextFocusableComponent(buttonAccept);
		fieldGroupNAme.setPreferredSize(new java.awt.Dimension(150, 22));
		fieldGroupNAme.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fieldGroupNAmeActionPerformed(evt);
			}
		});

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
		jPanel1.add(fieldGroupNAme, gridBagConstraints);

		add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

		buttonAccept.setText("Accept");
		buttonAccept.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonAcceptActionPerformed(evt);
			}
		});

		jPanel2.add(buttonAccept);

		buttonCancel.setText("Cancel");
		buttonCancel.setNextFocusableComponent(fieldQueryID);
		buttonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonCancelActionPerformed(evt);
			}
		});

		jPanel2.add(buttonCancel);

		add(jPanel2, java.awt.BorderLayout.SOUTH);

	}// </editor-fold>//GEN-END:initComponents

	private void fieldQueryIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldQueryIDActionPerformed
		// TODO add your handling code here:
		buttonAcceptActionPerformed(evt);
	}// GEN-LAST:event_fieldQueryIDActionPerformed

	private void buttonAcceptActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonAcceptActionPerformed
		String id = fieldQueryID.getText();
		String group = (String) comboGroups.getSelectedItem();

		QueryController qcontroller = queryController;

		boolean newgroup = false;

		if (group.equals(NOGROUP)) {
			group = null;
		} else if (group.equals(NEWGROUP)) {
			newgroup = true;
			group = fieldGroupNAme.getText();
		}

		int index = qcontroller.getElementPosition(id);

		if (index != -1) {
			JOptionPane
					.showMessageDialog(
							null,
							"Error: Query/Group with the same ID already exists.\nIDs must be unique. Please modify and try again.");
			return;
		}
		if (group == null) {
			qcontroller.addQuery(this.query, id);

		}
		if (newgroup) {
			qcontroller.createGroup(group);
			if (id != null)
				qcontroller.addQuery(this.query, id, group);

		}

		parent.dispose();
	}// GEN-LAST:event_buttonAcceptActionPerformed

	private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCancelActionPerformed
		parent.dispose();
	}// GEN-LAST:event_buttonCancelActionPerformed

	private void fieldGroupNAmeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldGroupNAmeActionPerformed
		// TODO add your handling code here:
		buttonAcceptActionPerformed(evt);
	}// GEN-LAST:event_fieldGroupNAmeActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonAccept;
	private javax.swing.JButton buttonCancel;
	private javax.swing.JComboBox comboGroups;
	private javax.swing.JTextField fieldGroupNAme;
	private javax.swing.JTextField fieldQueryID;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

}
