PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://fishdelish.cs.man.ac.uk/rdf/vocab/resource/>

SELECT ?type ?species ?genus ?country
WHERE {
   ?nameID :comnames_ComName "Aal" .
   ?nameID :comnames_NameType ?type .
   ?nameID :comnames_SpecCode ?code .
   ?nameID :comnames_C_Code ?ccode .
   ?code :species_Species ?species .
   ?code :species_Genus ?genus .
   ?ccode :countref_PAESE ?country .
}