PREFIX : <http://obda.inf.unibz.it/ontologies/tests/dllitef/test.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dllite: <http://obda.inf.unibz.it/ontologies/tests/dllitef/test.owl#>

SELECT ?y WHERE {?x dllite:R?y . ?x dllite:R?z . ?y dllite:S?m . ?z dllite:S?m}
