PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>SELECT DISTINCT $x $inst $type WHERE {      $x a :Transaction . 		$x a :Offer.		$x :involvesInstrument $inst. 		$inst a :Stock.		$inst :typeOfShares $type.}