PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://www.semanticweb.org/ontologies/2011/10/iLogOntology.owl#>  

# treni arrivati in ritardo

SELECT ?train ?tempo_partenza ?durata_schedulata ?tempo_arrivo
WHERE {
?train :isAssignedToRoute ?route.
?route :hasDestination ?stop.
?stop :hasScheduledStopTerminal ?terminal;
	:hasScheduledTime ?durata_schedulata.
?arrival :takesPlaceAt ?terminal;
	a :TrainArrival;
	:happensToTrain ?train;
	:hasEventTime ?tempo_arrivo.
?partenza a :TrainDeparture;
	:happensToTrain ?train;
	:hasEventTime ?tempo_partenza.
FILTER (?tempo_arrivo=?tempo_partenza &&
?tempo_arrivo="2011-11-11T00:00:00.000Z"^^xsd:dateTime).
}
ORDER BY ?train

