PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://www.semanticweb.org/ontologies/2011/10/iLogOntology.owl#>  

# terminal senza nessun TrainPassage [ossia, terminal non di transito] (utilizzo del terminal)

SELECT DISTINCT ?terminal
WHERE {
?event :takesPlaceAt ?terminal;
	:hasEventTime ?time.
FILTER( (?time > '2011-11-11T14:00:00.000Z'^^xsd:dateTime) &&
	 (?time <= '2011-11-11T15:00:00.000Z'^^xsd:dateTime))
OPTIONAL {
?passage :takesPlaceAt ?terminal;
	:hasEventTime ?time2;
	a :Passing.
FILTER( (?time2 > '2011-11-11T14:00:00.000Z'^^xsd:dateTime) &&
	 (?time2 <= '2011-11-11T15:00:00.000Z'^^xsd:dateTime))
}
FILTER (!bound(?passage))
}
ORDER BY ?terminal

