PREFIX  dc:  <http://purl.org/dc/elements/1.1/>
PREFIX  :  <http://example.org/>
SELECT  ?book (COALESCE(?Y, "none") as ?discount)
 WHERE {
   	?book a :Book ;
   	OPTIONAL { ?book :discount ?Y } 
}
