PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>SELECT DISTINCT * WHERE {      $x a :Address . 		$x :addressID $id. 		$x :inStreet $street. 		$x :inCity $city. 		$x :inCountry $country. 		$x :inState $state. 		$x :hasNumber $number. FILTER ( ( str($country) = "Italy" && $number = 3 ) || ( str($street) = "Via Marconi" && ( str($city) = "Bolzano" || str($street) = "Romer Street" ) ) ).}